### ISSUE TITLE
Please help re: pull request for tutorial

### ISSUE THREAD

**Issue by cg2p** [carbon-design-system/carbon-tutorial#10007]
## Summary
Can I check the steps need to submit the PR for the tutorial - as I am not seeing the Compare and Pull Request"?

I have followed this page:
https://carbondesignsystem.com/developing/react-tutorial/step-1/

and the final steps all complete successfully
```
yarn ci-check
git add --all && git commit -m "feat(tutorial): complete step 1"
git push origin v11-react-step-1
```

then I go to https://github.com/carbon-design-system/carbon-tutorial 
- Code page
- set the branch to v11-react-step-1 
- and do not see the Compare and Pull Request
 
does Netifly creates a draft PR for me to action - but not seeing the compare and pull request button to do that

Could you advise on correct steps please?

**Comment by Elmhaf** [comment]
don't go to https://github.com/carbon-design-system/carbon-tutorial but go to your forked repo and do a PR from there.
