### ISSUE TITLE
Node Sass version 7.0.1 is incompatible with ^4.0.0.

### ISSUE THREAD

**Issue by HassanFaisalwanclouds** [carbon-design-system/carbon-tutorial#10100]
Node Sass version 7.0.1 is incompatible with ^4.0.0.

./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/index.scss)
Error: Node Sass version 7.0.1 is incompatible with ^4.0.0.

GETTING THIS ERROR

let me know the exact commands to remove this

thankyou

**Comment by charlseo** [comment]
try to use sass rather than node-sass

```
- rm -rf node_modules
- yarn remove node-sass (npm uninstall node-sass)
-  yarn add sass
```

**Comment by HassanFaisalwanclouds** [comment]
fixed
