### ISSUE TITLE
Github GraphQL not working (502)

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon-tutorial#10813]
## Detailed description

> Describe in detail the issue you're having.

In step 3 a GraphQL query is introduced, which returns a `502`. This prevents further progression in the tutorial.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Broken query / GitHub API

> Is this issue related to a specific component?

RepoPage and RepoTable

> What did you expect to happen? What happened instead? What would you like to see changed?

A working GraphQL query.

I investigated the problem and it seems that the `releases` are the problem. Removing `releases` results in a successful query.
For some reason the `releases` are never used in the tutorial.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v11

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

n/a

## Steps to reproduce the issue

1. Start server
3. open http://localhost:3000/#/repos

## Additional information

This is the query which worked:
```graphql
gql`
  query REPO_QUERY {
    # Let's use carbon as our organization
    organization(login: "carbon-design-system") {
      # We'll grab all the repositories in one go. To load more resources
      # continuously, see the advanced topics.
      repositories(first: 75, orderBy: { field: UPDATED_AT, direction: DESC }) {
        totalCount
        nodes {
          url
          homepageUrl
          issues(filterBy: { states: OPEN }) {
            totalCount
          }
          stargazers {
            totalCount
          }
          name
          updatedAt
          createdAt
          description
          id
        }
      }
    }
  }
`
```

**Comment by tay1orjones** [comment]
@ConradSchmidt If you authorize your token with SSO does the error resolve? Here's an example of one that is authorized with SSO - if it's not the button will be a bit different and take you through a flow to sign in via SSO.

![image](https://user-images.githubusercontent.com/3360588/222209280-e4d07172-911b-4133-a47a-07091b0cd724.png)

This step should only apply to tokens generated by users who are members of the `carbon-design-system` organization on GitHub.
