### ISSUE TITLE
IBM Cloud instructions contain deprecated API names and are US-only

### ISSUE THREAD

**Issue by RoystonS** [carbon-design-system/carbon-tutorial#1790]
(From a Slack conversation in carbon-tutorial channel)

Step 5 of the Carbon tutorial tells people to log into IBM cloud using `api.ng.bluemix.net`.  There are a couple of problems with this:

1. This is a deprecated name, and should be `api.us-south.cf.cloud.ibm.com`  (see https://cloud.ibm.com/docs/overview?topic=overview-whatsnew&origin_team=T02M79KSB#new-cloud-foundry-api-endpoints).
2. If people log into the 'US South' region (as above), they'll only see spaces for the 'US South' region - and in fact will be told they have no organisations if they have no spaces in the 'US South' region.  The number 1 source of difficulty with troubleshooting Carbon Tutorial issues in my FED branch - which isn't US-based - has been getting this working.   It would be helpful to add some documentation to say either that the users should log into whatever region their spaces are in OR that they need to create a space in the 'US South' region.  If they don't do either of those they will get a lot of confusing errors.

**Comment by amaciejk** [comment]
+1 from me to get this fixed, for example I needed to use `cf login -a https://api.eu-gb.bluemix.net -sso` to not end up defaulting to the Org for the IBM product I work on which is in the ng region!

**Comment by RoystonS** [comment]
Nothing's changed.  The URLs that step 5 of the tutorial recommends are still deprecated and are still US-only.

**Comment by RoystonS** [comment]
The Carbon tutorial is _still_ using the hostname that IBM Cloud deprecated a long time ago, and it'll still be difficult to use for anybody outside of the US.

**Comment by RoystonS** [comment]
The Carbon tutorial is still using the hostname that IBM Cloud deprecated a long time ago, and it'll still be difficult to use for anybody outside of the US.

**Comment by RoystonS** [comment]
@alisonjoseph You've marked this with the 'question' label.  Are you waiting for something from me?

**Comment by JoseMiguelTM** [comment]
I solved your problem running ibmcloud commands on shell and that works for me, only that I have an issue with deployed app (exactly the page shows an 403 error..)
My steps for push to IBM Cloud are the following:

1. ibmcloud login
2. ibmcloud target -g MY_RESOURCE_GROUP
3. ibmcloud target --cf
4. ibmcloud cf
5. ibmcloud cf push -f manifest.yml

And that's all but I still have the issue with the deployed app...
I think the problem is for using nginx instead of buildpacks but sincerely I don't have any idea because I'm beginner on IBM Cloud
I hope this experience helps on your deployment issue, good luck!

**Comment by RoystonS** [comment]
@JoseMiguelTM Thanks. The issue I raised was about outdated documentation that's also confusing if you're not in the 'US South' region.  I did manage to get my group all sorted back in July last year but the documentation remains outdated and confusing.

**Comment by RoystonS** [comment]
@alisonjoseph You've marked this with the 'question' label. Are you waiting for something from me?

**Comment by tw15egan** [comment]
@RoystonS I'll get this updated on the website ASAP. Thanks for following through with this, and sorry for the confusion this has caused with your local FED branch 🙏
