### ISSUE TITLE
Step 1: explain what is happening with ci-check

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-tutorial#219]
https://github.com/carbon-design-system/carbon-tutorial/issues/94#issuecomment-497359026

**Comment by RoystonS** [comment]
I've only just spotted this after I'd already raised https://github.com/carbon-design-system/carbon-tutorial/issues/235.  There, I suggest that _explaining_ the odd behaviour will be painful and cause confusion for all Windows users, and that it might be nicer just to fix it by removing the offending line from `.editorconfig`.
