### ISSUE TITLE
Can't raise pull request for step 1 

### ISSUE THREAD

**Issue by smanikandan-btech** [carbon-design-system/carbon-tutorial#2429]
All,

I followed this link - https://www.carbondesignsystem.com/tutorial/react-step-1/ to setup and commit the files and try to create the pull request but I failed number of times. Only last step I'm failing.

Some time I'm facing permission denied problem

```
ERROR: Permission to carbon-design-system/carbon-tutorial.git denied to smanikandan-btech.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Thanks in advance.

**Comment by smanikandan-btech** [comment]
I can't get pull request option in my repo. Please check below screenshot.
<img width="861" alt="git1" src="https://user-images.githubusercontent.com/6849661/63152913-a15e9300-c02a-11e9-81fd-84ab4e5b63e1.png">

I tried in upstream repo also. same issue.
<img width="897" alt="git2" src="https://user-images.githubusercontent.com/6849661/63152914-a1f72980-c02a-11e9-9250-ce802677c843.png">

I have committed the codes from my local. Please check below screenshot.
<img width="633" alt="git3" src="https://user-images.githubusercontent.com/6849661/63152911-a15e9300-c02a-11e9-94af-560a56f8bf09.PNG">

Please, Please help me to move further. stuck in this from long time.

Thanks in advance.

**Comment by smanikandan-btech** [comment]
My step 1 preview is here - https://goofy-kalam-ac9583.netlify.com/#/

**Comment by smanikandan-btech** [comment]
Can anyone please help me on this?

**Comment by ZrianinaMariia** [comment]
Hey @smanikandan-btech. Could you please try to follow these steps:

1. Navigate to https://github.com/carbon-design-system/carbon-tutorial/pulls
2. Click on 'New Pull Request' green button
3. Click on 'compare across forks'
4. Select your fork as 'head repository' 
5. Select the correct branches for 'base' and 'compare', e.g. 'react-step-1'.
6. Click on 'Create Pull Request'

Let me know if it worked for you.

**Comment by smanikandan-btech** [comment]
Hi @ZrianinaMariia 

Thank you very much for your reply. I have followed the above steps. But I'm not finding my repo name listed in the list. For clear explanation I have taken screenshot and attached with this comment. Please have a look.

![github](https://user-images.githubusercontent.com/6849661/63278937-d33f5600-c2c5-11e9-9d34-63ad7dd059f0.png)

My github url is - https://github.com/smanikandan-btech/carbon-tutorial

**Comment by kellychurchill** [comment]
It appears that your repo was not created as a fork. Please start by following the steps here: 
https://www.carbondesignsystem.com/tutorial/react/step-1#fork-clone-and-branch

**Comment by smanikandan-btech** [comment]
Hi @kellychurchill, Thanks for your reply. It helped me to resolve the issue. 

Regards,
Mani
