### ISSUE TITLE
Why the tutorial website is down?

### ISSUE THREAD

**Issue by mahmoudkida** [carbon-design-system/carbon-tutorial#2436]
## Summary
Dear All,

I am trying to access the tutorial  website as I am currently in the last step but it gives error 404, Please advice

https://www.carbondesignsystem.com/tutorial/react-step-5

**Comment by spizzol** [comment]
The URL seems to have changed slightly:
https://www.carbondesignsystem.com/tutorial/react/step-5

**Comment by JoseMiguelTM** [comment]
I have the same issue
