### ISSUE TITLE
No mention of having to change the link to specific region when logging into IBM Cloud

### ISSUE THREAD

**Issue by Charlotte8699** [carbon-design-system/carbon-tutorial#2696]
<!-- Feel free to remove sections that aren't relevant.

## Title line template: [Title]: Brief description

No mention of having to change the link to specific region when logging into IBM Cloud

## Detailed description

> I followed the link provided in step 5 of the tutorial for logging into IBM cloud (when deploying). After spending some time trying to work out why it kept returning 'cf target -o ORG -s SPACE', it was realised that the regions in the URLs didn't match up so had the change them. It then worked. 

Although it eventually worked so it isn't a bug as such, it would be good to mention this in the tutorial for those of us in the UK and other areas outside the US.

## Steps to reproduce the issue

1. Step one
Follow '$ cf login -a https://api.ng.bluemix.net -sso'
And login from a UK based computer
2. Step two
Recieve: No org or space targeted, use 'cf target -o ORG -s SPACE'

**Comment by Charlotte8699** [comment]
This was the message I recieved

![Screenshot 2019-09-16 at 15 42 17](https://user-images.githubusercontent.com/52786879/64967550-a6686980-d898-11e9-9a09-af0f784a0649.png)


After changing it to 'https://api.eu-gb.bluemix.net', it worked.

**Comment by yumyo** [comment]
Great! Thank you @Charlotte8699
