### ISSUE TITLE
UI Shell Header Nav not showing Menu Items

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon-tutorial#3594]
Navigation bar no longer showing Repositories tab in Carbon Tutorial. Works when using a previous version of carbon components (10.3.0 and 7.3.0).

Reference https://github.com/carbon-design-system/carbon/issues/3546

**Comment by alisonjoseph** [comment]
Checked w/ @tw15egan and we don't think this is an issue anymore. Feel free to reopen if we missed anything 😅
