### ISSUE TITLE
React-Step-1: Import button from carbon-components-react not work

### ISSUE THREAD

**Issue by hintcnuie** [carbon-design-system/carbon-tutorial#3948]
## Detailed description
In the React Step 1,  there is import Button step:

> Next we’ll import a Button from Carbon to test that our dependencies are working properly. At the top of App.js, import the Button by adding the following:
`import { Button } from 'carbon-components-react';`

But when I run to this code, it always throws exception, I am on Mac using Node v8.17.0.

> Describe in detail the issue you're having.
```
Failed to compile
./node_modules/carbon-components-react/es/components/Icon/Icon.js
Module not found: Can't resolve 'carbon-icons' in '$HOME/Documents/CMDP/sourcecode/carbon-tutorial/node_modules/carbon-components-react/es/components/Icon'
```
> Is this a feature request (new component, new icon), a bug, or a general issue?
a bug 

> Is this issue related to a specific component?

Carbon-Icon

> What did you expect to happen? What happened instead? What would you like to see changed?

When I am using the below code, it works for me and error disappeard. I would like to know if this code should be updated into the Carbon tutorial guide.

`import Button from 'carbon-components-react/lib/components/Button/Button';`

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?
```
"dependencies": {
    "@carbon/icons-react": "^10.9.1",
    "carbon-components": "^10.10.1",
    "carbon-components-react": "^7.10.1",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.12.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router-dom": "^5.1.2",
    "react-scripts": "2.1.8"
  },
  "devDependencies": {
    "@commitlint/cli": "^7.5.2",
    "@commitlint/config-conventional": "^7.5.0",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.5",
    "node-sass": "^4.13.1",
    "prettier": "^1.17.0"
  },

```
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one

import a Button from Carbon using code:

> src/App.js

`import { Button } from 'carbon-components-react';`

2. Step two

> In the App component return, you can now replace:
>src/App.js

```
<div>
  Hello Carbon! Well, not quite yet. This is the starting point for the Carbon tutorial.
</div>
```
with:

`<Button>Button</Button>`

3. Step three
issue occurs

## Additional information

- Screenshots or code
- Notes
  Previously it was using

`import Button from 'carbon-components-react/lib/components/Button/Button';`

needs to be updated to how we previously imported Button as

import { Button } from 'carbon-components-react';

see 
https://github.com/carbon-design-system/carbon-tutorial/issues/44

**Comment by giacomobartoli** [comment]
I am experiencing the same issue. See https://github.com/carbon-design-system/carbon-tutorial/issues/3940
@alisonjoseph @mattrosno anyone to help us? thanks.
