### ISSUE TITLE
Unable to push local code using ssh

### ISSUE THREAD

**Issue by nabaraj** [carbon-design-system/carbon-tutorial#3959]
getting bellow error
$ git push origin react-step-1
ERROR: Permission to carbon-design-system/carbon-tutorial.git denied to nabaraj.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

using ssh key

**Comment by nabaraj** [comment]
got resoleved

**Comment by keyss-ankita** [comment]
hi @nabaraj how did you resolve this issue ?
