### ISSUE TITLE
dependency to deprecated version of fsevents

### ISSUE THREAD

**Issue by n006** [carbon-design-system/carbon-tutorial#4346]
## Detailed description

There seems to be a deprecated dependency to the fsevents module. Although the server starts a lot of errors appear while installing.
Am I missing something?

> warning Error running install script for optional dependency: "./node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: ./node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@12.16.3 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"./node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
[...]
> Failed to execute './.nvm/versions/node/v12.16.3/bin/node ./node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=./node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=./no✨

## Steps to reproduce the issue

$ git clone [fork of this repository]
$ cd carbon-tutorial
$ git remote add upstream https://github.com/carbon-design-system/carbon-tutorial.git
$ git fetch upstream
$ git checkout -b react-step-1 upstream/react-step-1
$ yarn

## Additional information

> macOS v10.15.4
> nvm 0.35.3
> node v12.16.3
> npm 6.14.4

**Comment by yairkukielka** [comment]
happening here too
