### ISSUE TITLE
Step 1 has inconsistent Button imports

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-tutorial#44]
The code snippet in https://www.carbondesignsystem.com/tutorial/react-step-1 that says

```javascript
import Button from 'carbon-components-react/lib/components/Button/Button';
```

needs to be updated to how we previously imported Button as

```javascript
import { Button } from 'carbon-components-react';
```

**Comment by hintcnuie** [comment]
I get this error when import the Button from carbon-components-react, but it pops up carbon-icons issue,   I'd like to know what's happening, thanks!
 

> Failed to compile
./node_modules/carbon-components-react/es/components/Icon/Icon.js
Module not found: Can't resolve 'carbon-icons' in '/Users/chenzhengwei/Documents/CMDP/sourcecode/carbon-tutorial/node_modules/carbon-components-react/es/components/Icon'
