### ISSUE TITLE
Can not push to github. Userid and password ok

### ISSUE THREAD

**Issue by zoranid** [carbon-design-system/carbon-tutorial#6041]
Zorans-MacBook-Pro:carbon-tutorial zoran@ibm.com$ git push origin react-step-1
Username for 'https://github.com': zoranid
Password for 'https://zoranid@github.com':
remote: Permission to carbon-design-system/carbon-tutorial.git denied to zoranid.
fatal: unable to access 'https://github.com/carbon-design-system/carbon-tutorial.git/': The requested URL returned error: 403

**Comment by tw15egan** [comment]
Seems like your origin is pointed at `carbon-design-system` and not your fork. 

See https://www.carbondesignsystem.com/developing/react-tutorial/step-1#add-upstream-remote

**Comment by zoranid** [comment]
Bad fork. Thanks. Submitted react-step-1
