### ISSUE TITLE
Remove CSS overrides, if possible

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-tutorial#6520]
We seed each tutorial step with a number of CSS overrides. It'd be nice to not need these. Can we evaluate these to see what's still needed?

https://github.com/carbon-design-system/carbon-tutorial/blob/react-step-1/src/index.css

These grid overrides are the most concerning:

https://github.com/carbon-design-system/carbon-tutorial/blob/react-step-2/src/index.scss

https://github.com/carbon-design-system/carbon-tutorial/blob/react-step-3/src/index.scss

https://github.com/carbon-design-system/carbon-tutorial/blob/react-step-4/src/index.scss

https://github.com/carbon-design-system/carbon-tutorial/blob/react-step-5/src/index.scss

CC @alisonjoseph @tw15egan

**Comment by tw15egan** [comment]
If you remove them does the preview look the same? Otherwise, we'll still need them

**Comment by alisonjoseph** [comment]
I think we need all those overrides still, other than maybe the ui-shell feature flag?
