### ISSUE TITLE
Step 3 -> Step 4 not working (GitHub API gives 401 ERROR)

### ISSUE THREAD

**Issue by georg90** [carbon-design-system/carbon-tutorial#7876]
## Detailed description

When trying Step 3 of the attached tutorial: https://www.carbondesignsystem.com/developing/react-tutorial/step-3
I receive an 401 HTTP ERROR when implementing the API Call to Github

```
const client = new ApolloClient({
  uri: 'https://api.github.com/graphql',
  headers: {
    authorization: `Bearer ${process.env.REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN}`,
  },
});
```

Error returned on react webapp: 
```
TypeError: Cannot read property 'organization' of undefined
```
> What did you expect to happen? What happened instead? What would you like to see changed?

API should return 200

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

1. Checkout the tutorial step 4 (!)
2. try to start with `yarn` and `yarn start`
3. See error page

**Comment by Paula-Cremerius** [comment]
I had a similar issue from my .env.local file stored on the wrong folder level and therefore not being picked up, placing it next to .env helped
