### ISSUE TITLE
Step 4: Missing a DAP violation

### ISSUE THREAD

**Issue by timmawson** [carbon-design-system/carbon-tutorial#847]
Running the DAP tool at the completion of the Step 4 carbon component tutorial shows 5 violations, rather than the 4 shown in the tutorial page. 

There are 4 violations for the <article> elements, as expected, plus one for the <section> element (missing aria-label or aria-labelledby) that is not mentioned.

![image](https://user-images.githubusercontent.com/51777005/59698953-9df48a00-91e8-11e9-8c24-72b555ce705a.png)

(seen in the screen shot under "Elements containing a 'region' role must be labeled with aria-label or arial-labelledby.")

**Comment by mattrosno** [comment]
hi @timmawson what Carbon version is this with? wondering if it's something new with 10.3.1. also, what component is using the `region` role?

**Comment by timmawson** [comment]
Apologies, I believe this issue can be closed - I think I was using the wrong ruleset. Using Feb 2019 rules the DAPs violations are as expected.

**Comment by mattrosno** [comment]
Great! Thanks for submitting the issue, and for following up. We appreciate it! I'll close.
