### ISSUE TITLE
Node 17 mac 1st step of tutorial

### ISSUE THREAD

**Issue by Corrigan14** [carbon-design-system/carbon-tutorial#9708]
## Detailed description
After following the tutorial, I couldn't start the app on node 27, had to downgrade to 16 to get it working

**Comment by carlosblanc0** [comment]
I've recently opened a similar issue [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template/issues/146). I'm a firm believer that this simple "feature" if you will, would drastically increase productivity levels.
